# Generated by Django 5.1.4 on 2026-09-16 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(unique=True, verbose_name='Sürüm')),
                ('source', models.CharField(choices=[('admin', 'Django Admin'), ('pos', 'Windows POS')], default='admin', max_length=10, verbose_name='Kaynak')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Yayım Tarihi')),
                ('snapshot', models.JSONField(verbose_name='Katalog Anlık Görüntüsü')),
            ],
            options={
                'verbose_name': 'Katalog Sürümü',
                'verbose_name_plural': 'Katalog Sürümleri',
                'ordering': ['-version'],
                'get_latest_by': 'version',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=60, unique=True, verbose_name='Kategori Kodu')),
                ('name', models.CharField(max_length=160, verbose_name='Kategori Adı')),
                ('display_order', models.IntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=80, unique=True, verbose_name='Cihaz Kimliği')),
                ('name', models.CharField(default='POS', max_length=100, verbose_name='Cihaz Adı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Son Senkronizasyon')),
            ],
            options={
                'verbose_name': 'Cihaz',
                'verbose_name_plural': 'Cihazlar',
            },
        ),
        migrations.CreateModel(
            name='CashMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_id', models.CharField(max_length=80, unique=True, verbose_name='Hareket Kimliği')),
                ('shift_id', models.CharField(max_length=80, verbose_name='Vardiya')),
                ('amount', models.IntegerField(verbose_name='Tutar (kuruş)')),
                ('reason', models.CharField(max_length=300, verbose_name='Açıklama')),
                ('occurred_at', models.DateTimeField(verbose_name='Zaman')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.device', verbose_name='Cihaz')),
            ],
            options={
                'verbose_name': 'Kasa Hareketi',
                'verbose_name_plural': 'Kasa Hareketleri',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=80, unique=True, verbose_name='Sipariş Kimliği')),
                ('table_id', models.CharField(max_length=20, verbose_name='Masa')),
                ('status', models.CharField(max_length=20, verbose_name='Durum')),
                ('opened_at', models.DateTimeField(verbose_name='Açılış Zamanı')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Kapanış Zamanı')),
                ('body', models.JSONField(verbose_name='Sipariş Verisi')),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.device', verbose_name='Cihaz')),
            ],
            options={
                'verbose_name': 'Sipariş',
                'verbose_name_plural': 'Siparişler',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=80, unique=True, verbose_name='Ödeme Kimliği')),
                ('shift_id', models.CharField(max_length=80, verbose_name='Vardiya')),
                ('method', models.CharField(choices=[('cash', 'Nakit'), ('card', 'Kart'), ('meal', 'Yemek Kartı'), ('gift', 'İkram')], max_length=10, verbose_name='Yöntem')),
                ('total', models.IntegerField(verbose_name='Tutar (kuruş)')),
                ('gift', models.IntegerField(default=0, verbose_name='İkram Tutarı (kuruş)')),
                ('occurred_at', models.DateTimeField(verbose_name='Zaman')),
                ('body', models.JSONField(verbose_name='Ödeme Verisi')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.device', verbose_name='Cihaz')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='pos.order', verbose_name='Sipariş')),
            ],
            options={
                'verbose_name': 'Ödeme',
                'verbose_name_plural': 'Ödemeler',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=60, unique=True, verbose_name='Ürün Kodu')),
                ('name', models.CharField(max_length=160, verbose_name='Ürün Adı')),
                ('price', models.IntegerField(verbose_name='Fiyat (kuruş)')),
                ('active', models.BooleanField(default=True, verbose_name='Satışta')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('image', models.CharField(blank=True, max_length=200, verbose_name='Görsel yolu')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='pos.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['category__display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_id', models.CharField(max_length=80, unique=True, verbose_name='Vardiya Kimliği')),
                ('opened_at', models.DateTimeField(verbose_name='Açılış')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Kapanış')),
                ('opening_cash', models.IntegerField(default=0, verbose_name='Açılış Nakdi (kuruş)')),
                ('revenue', models.IntegerField(default=0, verbose_name='Ciro (kuruş)')),
                ('totals', models.JSONField(default=dict, verbose_name='Toplamlar')),
                ('body', models.JSONField(default=dict, verbose_name='Tam Rapor')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.device', verbose_name='Cihaz')),
            ],
            options={
                'verbose_name': 'Vardiya',
                'verbose_name_plural': 'Vardiyalar',
                'ordering': ['-closed_at'],
            },
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200, verbose_name='Dosya Adı')),
                ('size_bytes', models.IntegerField(verbose_name='Boyut (bayt)')),
                ('file', models.FileField(upload_to='backups/%Y/%m/', verbose_name='Dosya')),
                ('stored_at', models.DateTimeField(auto_now_add=True, verbose_name='Depolama Tarihi')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.device', verbose_name='Cihaz')),
            ],
            options={
                'verbose_name': 'Yedek',
                'verbose_name_plural': 'Yedekler',
                'ordering': ['-stored_at'],
                'unique_together': {('device', 'filename')},
            },
        ),
        migrations.CreateModel(
            name='SyncEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=80, unique=True, verbose_name='Olay Kimliği')),
                ('seq', models.IntegerField(verbose_name='Sıra No')),
                ('kind', models.CharField(choices=[('catalog', 'Katalog'), ('order', 'Sipariş'), ('payment', 'Ödeme'), ('void', 'İptal'), ('cash', 'Kasa Hareketi'), ('day-close', 'Gün Sonu'), ('security', 'Güvenlik')], max_length=30, verbose_name='Tür')),
                ('occurred_at', models.DateTimeField(verbose_name='Oluşma Zamanı')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Alınma Zamanı')),
                ('payload', models.JSONField(default=dict, verbose_name='İçerik')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.device', verbose_name='Cihaz')),
            ],
            options={
                'verbose_name': 'Senkronizasyon Olayı',
                'verbose_name_plural': 'Senkronizasyon Olayları',
                'ordering': ['device', 'seq'],
                'unique_together': {('device', 'seq')},
            },
        ),
    ]
