# Generated by Django 5.1.4 on 2026-09-16 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.CharField(max_length=60, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_-]{1,60}$', 'Yalnızca İngilizce harf, rakam, alt çizgi ve tire kullanın (en fazla 60 karakter). Windows POS bu biçimi zorunlu tutar.')], verbose_name='Kategori Kodu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(help_text='Boş bırakırsanız ürün adından otomatik üretilir. Sonradan değiştirilemez.', max_length=60, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_-]{1,60}$', 'Yalnızca İngilizce harf, rakam, alt çizgi ve tire kullanın (en fazla 60 karakter). Windows POS bu biçimi zorunlu tutar.')], verbose_name='Ürün Kodu'),
        ),
    ]
