# Generated by Django 5.1.4 on 2026-09-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_backfill_blank_product_ids'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category__display_order', 'sort_order', 'name'], 'verbose_name': 'Ürün', 'verbose_name_plural': 'Ürünler'},
        ),
        migrations.RemoveField(
            model_name='syncevent',
            name='payload',
        ),
        migrations.AddField(
            model_name='product',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Sıra'),
        ),
    ]
