# Generated by Django 5.1.4 on 2026-09-16 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_alter_product_options_remove_syncevent_payload_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Ürün', 'verbose_name_plural': 'Ürünler'},
        ),
    ]
